### ISSUE TITLE
Crash when asking a question！！！

### ISSUE THREAD

**Issue by zlwleng** [go-skynet/LocalAI#112]
Asking A Question:  
```
curl --location 'http://127.0.0.1:8080/v1/completions' \
--header 'Content-Type: application/json' \
--data '{
    "model": "ggml-gpt4all-j",
    "temperature": 0.9,
    "prompt": "How are you?"
}'
```

Run Log:
```
Attaching to localai-api-1
localai-api-1  | 
localai-api-1  |  ┌───────────────────────────────────────────────────┐ 
localai-api-1  |  │                   Fiber v2.44.0                   │ 
localai-api-1  |  │               http://127.0.0.1:8080               │ 
localai-api-1  |  │       (bound on host 0.0.0.0 and port 8080)       │ 
localai-api-1  |  │                                                   │ 
localai-api-1  |  │ Handlers ............ 10  Processes ........... 1 │ 
localai-api-1  |  │ Prefork ....... Disabled  PID ................. 1 │ 
localai-api-1  |  └───────────────────────────────────────────────────┘ 
localai-api-1  | 
localai-api-1  | llama.cpp: loading model from /models/ggml-gpt4all-j
localai-api-1 exited with code 0
```

Error:
`Error: socket hang up` And `Running program crashes`

**Comment by LarsBingBong** [comment]
We would need you to let us know how you're running `Local-AI`.

- Through Docker Desktop?
- What OS

And so on and so forth.

**Comment by kentative** [comment]
same problem for me: 
Dock Desktop () on Windows (Version 10.0.22621 Build 22621)

`2023-05-01 15:38:53 gptj_model_load: loading model from '/models/ggml-gpt4all-j.bin' - please wait ...
2023-05-01 15:38:53 gptj_model_load: n_vocab = 50400
2023-05-01 15:38:53 gptj_model_load: n_ctx   = 2048
2023-05-01 15:38:53 gptj_model_load: n_embd  = 4096
2023-05-01 15:38:53 gptj_model_load: n_head  = 16
2023-05-01 15:38:53 gptj_model_load: n_layer = 28
2023-05-01 15:38:53 gptj_model_load: n_rot   = 64
2023-05-01 15:38:53 gptj_model_load: f16     = 2
2023-05-01 15:38:53 gptj_model_load: ggml ctx size = 5401.45 MB
2023-05-01 15:38:53 gptj_model_load: memory_size =  1792.00 MB, n_mem = 57344
2023-05-01 15:38:57 gptj_model_load: ................................... done
2023-05-01 15:38:57 gptj_model_load: model size =  3609.38 MB / num tensors = 285
2023-05-01 15:38:58 fatal error: unexpected signal during runtime execution
2023-05-01 15:38:58 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f45bfafd2f2]
2023-05-01 15:38:58 
2023-05-01 15:38:58 runtime stack:
2023-05-01 15:38:58 runtime.throw({0xa33a54?, 0x2000?})
2023-05-01 15:38:58     /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7ffcd0a34388 sp=0x7ffcd0a34358 pc=0x4524dd
2023-05-01 15:38:58 runtime.sigpanic()
2023-05-01 15:38:58     /usr/local/go/src/runtime/signal_unix.go:821 +0x3e9 fp=0x7ffcd0a343e8 sp=0x7ffcd0a34388 pc=0x468569
2023-05-01 15:38:58 
2023-05-01 15:38:58 goroutine 22 [syscall]:
2023-05-01 15:38:58 runtime.cgocall(0x8cf120, 0xc0002a8ef8)
2023-05-01 15:38:58     /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0002a8ed0 sp=0xc0002a8e98 pc=0x42175c
2023-05-01 15:38:58 github.com/go-skynet/go-gpt4all-j%2ecpp._Cfunc_binding_model_prompt(0x198d640, 0x11e1ab0, 0xc000392000, 0xa, 0x3f99999a, 0x400, 0x200, 0x50, 0x3f333333, 0x3f666666, ...)
2023-05-01 15:38:58     _cgo_gotypes.go:113 +0x45 fp=0xc0002a8ef8 sp=0xc0002a8ed0 pc=0x5c0c85
2023-05-01 15:38:58 github.com/go-skynet/go-gpt4all-j%2ecpp.(*GPTJ).Predict.func1(0x43e6e7?, 0x5c525e?, {0xc000392000, 0xc0002a9040?, 0x43e825?}, {0x400, 0xa, 0x200, 0x50, 0x1, ...})
2023-05-01 15:38:58     /build/go-gpt4all-j/gptj.go:52 +0x185 fp=0xc0002a8fa0 sp=0xc0002a8ef8 pc=0x5c16c5
2023-05-01 15:38:58 github.com/go-skynet/go-gpt4all-j%2ecpp.(*GPTJ).Predict(0xc000380340?, {0x0, 0x0}, {0xc0002a91a8, 0x4, 0x7f4596dcfc78?})
2023-05-01 15:38:58     /build/go-gpt4all-j/gptj.go:52 +0x225 fp=0xc0002a9100 sp=0xc0002a8fa0 pc=0x5c1345
2023-05-01 15:38:58 github.com/go-skynet/LocalAI/api.ModelInference.func3()
2023-05-01 15:38:58     /build/api/prediction.go:117 +0x23b fp=0xc0002a91d8 sp=0xc0002a9100 pc=0x8852db
2023-05-01 15:38:58 github.com/go-skynet/LocalAI/api.ModelInference.func5()
2023-05-01 15:38:58     /build/api/prediction.go:183 +0x184 fp=0xc0002a9270 sp=0xc0002a91d8 pc=0x884684
2023-05-01 15:38:58 github.com/go-skynet/LocalAI/api.ComputeChoices({0x0, 0x0}, 0xc000301b00, 0xc000360180, 0xc00031adf0?, 0xc0002a9858)
2023-05-01 15:38:58     /build/api/prediction.go:203 +0x224 fp=0xc0002a9728 sp=0xc0002a9270 pc=0x885f04
2023-05-01 15:38:58 github.com/go-skynet/LocalAI/api.chatEndpoint.func1(0xc000160b00)
2023-05-01 15:38:58     /build/api/openai.go:315 +0x605 fp=0xc0002a98b8 sp=0xc0002a9728 pc=0x882aa5
2023-05-01 15:38:58 github.com/gofiber/fiber/v2.(*App).next(0xc000311b00, 0xc000160b00)
2023-05-01 15:38:58     /go/pkg/mod/github.com/gofiber/fiber/v2@v2.44.0/router.go:144 +0x1bf fp=0xc0002a9960 sp=0xc0002a98b8 pc=0x84551f
2023-05-01 15:38:58 github.com/gofiber/fiber/v2.(*Ctx).Next(0xc000352330?)
2023-05-01 15:38:58     /go/pkg/mod/github.com/gofiber/fiber/v2@v2.44.0/ctx.go:913 +0x53 fp=0xc0002a9980 sp=0xc0002a9960 pc=0x830b13
2023-05-01 15:38:58 github.com/gofiber/fiber/v2/middleware/cors.New.func1(0xc000160b00)
2023-05-01 15:38:58     /go/pkg/mod/github.com/gofiber/fiber/v2@v2.44.0/middleware/cors/cors.go:162 +0x3a6 fp=0xc0002a9a98 sp=0xc0002a9980 pc=0x84b2e6
2023-05-01 15:38:58 github.com/gofiber/fiber/v2.(*Ctx).Next(0x14?)
2023-05-01 15:38:58     /go/pkg/mod/github.com/gofiber/fiber/v2@v2.44.0/ctx.go:910 +0x43 fp=0xc0002a9ab8 sp=0xc0002a9a98 pc=0x830b03
2023-05-01 15:38:58 github.com/gofiber/fiber/v2/middleware/recover.New.func1(0x9a6ca0?)
2023-05-01 15:38:58     /go/pkg/mod/github.com/gofiber/fiber/v2@v2.44.0/middleware/recover/recover.go:43 +0xcb fp=0xc0002a9b30 sp=0xc0002a9ab8 pc=0x84bf0b
2023-05-01 15:38:58 github.com/gofiber/fiber/v2.(*App).next(0xc000311b00, 0xc000160b00)
2023-05-01 15:38:58     /go/pkg/mod/github.com/gofiber/fiber/v2@v2.44.0/router.go:144 +0x1bf fp=0xc0002a9bd8 sp=0xc0002a9b30 pc=0x84551f
2023-05-01 15:38:58 github.com/gofiber/fiber/v2.(*App).handler(0xc000311b00, 0x4a59f7?)
2023-05-01 15:38:58     /go/pkg/mod/github.com/gofiber/fiber/v2@v2.44.0/router.go:171 +0x87 fp=0xc0002a9c38 sp=0xc0002a9bd8 pc=0x845767
2023-05-01 15:38:58 github.com/gofiber/fiber/v2.(*App).handler-fm(0xc000352000?)
2023-05-01 15:38:58     <autogenerated>:1 +0x2c fp=0xc0002a9c58 sp=0xc0002a9c38 pc=0x84a98c
2023-05-01 15:38:58 github.com/valyala/fasthttp.(*Server).serveConn(0xc00032e000, {0xadd600?, 0xc000126428})
2023-05-01 15:38:58     /go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/server.go:2365 +0x11d3 fp=0xc0002a9ec8 sp=0xc0002a9c58 pc=0x7cb893
2023-05-01 15:38:58 github.com/valyala/fasthttp.(*Server).serveConn-fm({0xadd600?, 0xc000126428?})
2023-05-01 15:38:58     <autogenerated>:1 +0x39 fp=0xc0002a9ef0 sp=0xc0002a9ec8 pc=0x7db159
2023-05-01 15:38:58 github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc00013fb80, 0xc00032c2a0)
2023-05-01 15:38:58     /go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:224 +0xa9 fp=0xc0002a9fa0 sp=0xc0002a9ef0 pc=0x7d7389
2023-05-01 15:38:58 github.com/valyala/fasthttp.(*workerPool).getCh.func1()
2023-05-01 15:38:58     /go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:196 +0x38 fp=0xc0002a9fe0 sp=0xc0002a9fa0 pc=0x7d70f8
2023-05-01 15:38:58 runtime.goexit()
2023-05-01 15:38:58     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0002a9fe8 sp=0xc0002a9fe0 pc=0x483b61
2023-05-01 15:38:58 created by github.com/valyala/fasthttp.(*workerPool).getCh
2023-05-01 15:38:58     /go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:195 +0x1b0
2023-05-01 15:38:58 
2023-05-01 15:38:58 goroutine 1 [IO wait]:
2023-05-01 15:38:58 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc0002d3478 sp=0xc0002d3458 pc=0x4551f6
2023-05-01 15:38:58 runtime.netpollblock(0x44cd54?, 0x420def?, 0x0?)
2023-05-01 15:38:58     /usr/local/go/src/runtime/netpoll.go:527 +0xf7 fp=0xc0002d34b0 sp=0xc0002d3478 pc=0x44db57
2023-05-01 15:38:58 internal/poll.runtime_pollWait(0x7f4596dd6940, 0x72)
2023-05-01 15:38:58     /usr/local/go/src/runtime/netpoll.go:306 +0x89 fp=0xc0002d34d0 sp=0xc0002d34b0 pc=0x47e869
2023-05-01 15:38:58 internal/poll.(*pollDesc).wait(0xc00017ee00?, 0xde4ec0?, 0x0)
2023-05-01 15:38:58     /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32 fp=0xc0002d34f8 sp=0xc0002d34d0 pc=0x4ba8b2
2023-05-01 15:38:58 internal/poll.(*pollDesc).waitRead(...)
2023-05-01 15:38:58     /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
2023-05-01 15:38:58 internal/poll.(*FD).Accept(0xc00017ee00)
2023-05-01 15:38:58     /usr/local/go/src/internal/poll/fd_unix.go:614 +0x2bd fp=0xc0002d35a0 sp=0xc0002d34f8 pc=0x4c01bd
2023-05-01 15:38:58 net.(*netFD).accept(0xc00017ee00)
2023-05-01 15:38:58     /usr/local/go/src/net/fd_unix.go:172 +0x35 fp=0xc0002d3658 sp=0xc0002d35a0 pc=0x56fe55
2023-05-01 15:38:58 net.(*TCPListener).accept(0xc000130828)
2023-05-01 15:38:58     /usr/local/go/src/net/tcpsock_posix.go:148 +0x25 fp=0xc0002d3680 sp=0xc0002d3658 pc=0x5860c5
2023-05-01 15:38:58 net.(*TCPListener).Accept(0xc000130828)
2023-05-01 15:38:58     /usr/local/go/src/net/tcpsock.go:297 +0x3d fp=0xc0002d36b0 sp=0xc0002d3680 pc=0x5851bd
2023-05-01 15:38:58 github.com/valyala/fasthttp.acceptConn(0xc00032e000, {0xadad40, 0xc000130828}, 0xc0002d38a8)
2023-05-01 15:38:58     /go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/server.go:1930 +0x62 fp=0xc0002d3790 sp=0xc0002d36b0 pc=0x7c9d62
2023-05-01 15:38:58 github.com/valyala/fasthttp.(*Server).Serve(0xc00032e000, {0xadad40?, 0xc000130828})
2023-05-01 15:38:58     /go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/server.go:1823 +0x4f4 fp=0xc0002d38d8 sp=0xc0002d3790 pc=0x7c9374
2023-05-01 15:38:58 github.com/gofiber/fiber/v2.(*App).Listen(0xc000311b00, {0xa1706e?, 0x7?})
2023-05-01 15:38:58     /go/pkg/mod/github.com/gofiber/fiber/v2@v2.44.0/listen.go:82 +0x110 fp=0xc0002d3938 sp=0xc0002d38d8 pc=0x83c630
2023-05-01 15:38:58 main.main.func1(0xc0002d3c00?)
2023-05-01 15:38:58     /build/main.go:88 +0x245 fp=0xc0002d39f0 sp=0xc0002d3938 pc=0x8c01c5
2023-05-01 15:38:58 github.com/urfave/cli/v2.(*Command).Run(0xc000320160, 0xc000112b80, {0xc000128000, 0x2, 0x2})
2023-05-01 15:38:58     /go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/command.go:274 +0x9eb fp=0xc0002d3c90 sp=0xc0002d39f0 pc=0x8ae32b
2023-05-01 15:38:58 github.com/urfave/cli/v2.(*App).RunContext(0xc00031c000, {0xadb088?, 0xc000132000}, {0xc000128000, 0x2, 0x2})
2023-05-01 15:38:58     /go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/app.go:332 +0x616 fp=0xc0002d3d00 sp=0xc0002d3c90 pc=0x8ab136
2023-05-01 15:38:58 github.com/urfave/cli/v2.(*App).Run(...)
2023-05-01 15:38:58     /go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/app.go:309
2023-05-01 15:38:58 main.main()
2023-05-01 15:38:58     /build/main.go:92 +0x997 fp=0xc0002d3f80 sp=0xc0002d3d00 pc=0x8bfeb7
2023-05-01 15:38:58 runtime.main()
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc0002d3fe0 sp=0xc0002d3f80 pc=0x454dc7
2023-05-01 15:38:58 runtime.goexit()
2023-05-01 15:38:58     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0002d3fe8 sp=0xc0002d3fe0 pc=0x483b61
2023-05-01 15:38:58 
2023-05-01 15:38:58 goroutine 2 [force gc (idle)]:
2023-05-01 15:38:58 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060fb0 sp=0xc000060f90 pc=0x4551f6
2023-05-01 15:38:58 runtime.goparkunlock(...)
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:387
2023-05-01 15:38:58 runtime.forcegchelper()
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000060fe0 sp=0xc000060fb0 pc=0x455030
2023-05-01 15:38:58 runtime.goexit()
2023-05-01 15:38:58     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000060fe8 sp=0xc000060fe0 pc=0x483b61
2023-05-01 15:38:58 created by runtime.init.6
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:293 +0x25
2023-05-01 15:38:58 
2023-05-01 15:38:58 goroutine 18 [GC sweep wait]:
2023-05-01 15:38:58 runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00005c780 sp=0xc00005c760 pc=0x4551f6
2023-05-01 15:38:58 runtime.goparkunlock(...)
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:387
2023-05-01 15:38:58 runtime.bgsweep(0x0?)
2023-05-01 15:38:58     /usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc00005c7c8 sp=0xc00005c780 pc=0x44142e
2023-05-01 15:38:58 runtime.gcenable.func1()
2023-05-01 15:38:58     /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc00005c7e0 sp=0xc00005c7c8 pc=0x436706
2023-05-01 15:38:58 runtime.goexit()
2023-05-01 15:38:58     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x483b61
2023-05-01 15:38:58 created by runtime.gcenable
2023-05-01 15:38:58     /usr/local/go/src/runtime/mgc.go:178 +0x6b
2023-05-01 15:38:58 
2023-05-01 15:38:58 goroutine 19 [GC scavenge wait]:
2023-05-01 15:38:58 runtime.gopark(0xc00010e000?, 0xad3ad0?, 0x1?, 0x0?, 0x0?)
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00005cf70 sp=0xc00005cf50 pc=0x4551f6
2023-05-01 15:38:58 runtime.goparkunlock(...)
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:387
2023-05-01 15:38:58 runtime.(*scavengerState).park(0xe76c40)
2023-05-01 15:38:58     /usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc00005cfa0 sp=0xc00005cf70 pc=0x43f373
2023-05-01 15:38:58 runtime.bgscavenge(0x0?)
2023-05-01 15:38:58     /usr/local/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc00005cfc8 sp=0xc00005cfa0 pc=0x43f945
2023-05-01 15:38:58 runtime.gcenable.func2()
2023-05-01 15:38:58     /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc00005cfe0 sp=0xc00005cfc8 pc=0x4366a6
2023-05-01 15:38:58 runtime.goexit()
2023-05-01 15:38:58     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x483b61
2023-05-01 15:38:58 created by runtime.gcenable
2023-05-01 15:38:58     /usr/local/go/src/runtime/mgc.go:179 +0xaa
2023-05-01 15:38:58 
2023-05-01 15:38:58 goroutine 20 [finalizer wait]:
2023-05-01 15:38:58 runtime.gopark(0x1a0?, 0xe77920?, 0x20?, 0x28?, 0xc000060770?)
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000060628 sp=0xc000060608 pc=0x4551f6
2023-05-01 15:38:58 runtime.runfinq()
2023-05-01 15:38:58     /usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000607e0 sp=0xc000060628 pc=0x435747
2023-05-01 15:38:58 runtime.goexit()
2023-05-01 15:38:58     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000607e8 sp=0xc0000607e0 pc=0x483b61
2023-05-01 15:38:58 created by runtime.createfing
2023-05-01 15:38:58     /usr/local/go/src/runtime/mfinal.go:163 +0x45
2023-05-01 15:38:58 
2023-05-01 15:38:58 goroutine 21 [sleep]:
2023-05-01 15:38:58 runtime.gopark(0xcb6a44d0ec7?, 0xc00005d788?, 0x65?, 0x4a?, 0xc00013fbb0?)
2023-05-01 15:38:58     /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc00005d758 sp=0xc00005d738 pc=0x4551f6
2023-05-01 15:38:58 time.Sleep(0x2540be400)
2023-05-01 15:38:58     /usr/local/go/src/runtime/time.go:195 +0x135 fp=0xc00005d798 sp=0xc00005d758 pc=0x4809d5
2023-05-01 15:38:58 github.com/valyala/fasthttp.(*workerPool).Start.func2()
2023-05-01 15:38:58     /go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:67 +0x56 fp=0xc00005d7e0 sp=0xc00005d798 pc=0x7d6856
2023-05-01 15:38:58 runtime.goexit()
2023-05-01 15:38:58     /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00005d7e8 sp=0xc00005d7e0 pc=0x483b61
2023-05-01 15:38:58 created by github.com/valyala/fasthttp.(*workerPool).Start
2023-05-01 15:38:58     /go/pkg/mod/github.com/valyala/fasthttp@v1.47.0/workerpool.go:59 +0xdd
`

**Comment by Aisuko** [comment]
Hi guys, thanks for your feedback. Do you guys all hit the issue on Windows?

**Comment by gregoryca** [comment]
i have the same issue on ubuntu 22.0.4, running the latest version of docker 
![localai](https://github.com/go-skynet/LocalAI/assets/10562868/3757998d-b1b2-49de-baf2-1a5e2bc9d846)

**Comment by anhhtca** [comment]
You must build your own image and use it. Do not pull a pre-built image from Docker Hub as it can sometimes lead to crashes.

I have built my own image, which took a long time. The answer is also long.

**Comment by gregoryca** [comment]
@anhhtca Thank you very much for your quick answer ! In my case it had configured traefik incorrectly.

After fixing that issue, another issue arose which cannot be fixed easily, but it's not really a blocker either.
I run out of resources when promting the container.
![localai-loadaverage-grafana](https://github.com/go-skynet/LocalAI/assets/10562868/f2cbdb7c-90d8-4301-b51d-b35f164b6103)

It can take up to a minute for the ai to anwer my prompts. Luckily it does work, only with a heavy performance penalty (i''m running my whole infra from a intel 3210m core i5 2.5ghz and 16gb ram with a 256 gb SSD)

**Comment by gregoryca** [comment]
i want to add to this cause i kept banging my head at this issue when loading other models.
Make sure you use models from the model gallery, and if you're using a huggingface model, make sure to select the huggingface wrapper in your UI as it will crash becasue it probably does not know how to handle the data calculations when running a query making it crash.

You could also check if your CPU does support avx(2) As i've found some threads regarding AVX(2) instructionset being mandatory when running a build.

**Comment by Aisuko** [comment]
If the latest version of LocalAI still crashed feel free to open new issue. I am going to close this one.
