### ISSUE TITLE
No Module/Attribute

### ISSUE THREAD

**Issue by NickDeBeenSAE** [go-skynet/LocalAI#887]
<pre>(gpt4all) [insertusernamehere@fedora python]$ python3 -c "import gpt4all; print(gpt4all.models.list_models())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'gpt4all' has no attribute 'models'
(gpt4all) [insertusernamehere@fedora python]$ python3 -c "import gpt4all_bindings.python; print(gpt4all.models.list_models())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'gpt4all_bindings'<pre>

There appears to be no module nor attribute for gpt4all_bindings in the pypi archives.

**Comment by NickDeBeenSAE** [comment]
There appears to be no modules nor attributes that get installed when using the following python command:

<pre>python3 install -e .<pre>
